export interface AtlasPosition {
  // PositionGroupID: string,
  // Department: string,
  // DepartmentID: number,
  // InstitutionName:string,
  // InstitutionID: number,
  // IsActive: boolean,
  // School: string,
  // AvailablePositions: number,
  city: string,
  // CityID: number,
  // contactPhone: string,
  // country: string,
  // countryID: number,
  description: string,
  positionType: string,
  // duration: number,
  // endDate: null,
  // endDateString: number,
  // hasTimeLimit: boolean,
  // ID: 3,
  // isAvailableToAllAcademics: boolean,
  // PhysicalObjects: string,
  // prefecture: string,
  // prefectureID: number,
  // startDate: string,
  // startDateString: string,
  // supervisor: string,
  // supervisorEmail: string,
  // timeLimit: string,
  title: string,
  name: string,
  // positionGroupLastUpdateString: string,
  // providerAFM: string,
  providerContactEmail: string,
  providerContactName: string,
  providerContactPhone: string,
  // providerID: number,
  // providerName: string,
  // providerLastUpdateString: string;
}
