export interface AtlasPosition {
  // PositionGroupID: string,
  // Department: string,
  // DepartmentID: number,
  // InstitutionName:string,
  // InstitutionID: number,
  // IsActive: boolean,
  // School: string,
  // AvailablePositions: number,
  City: string,
  // CityID: number,
  // contactPhone: string,
  // country: string,
  // countryID: number,
  // description: string
  // duration: number,
  // endDate: null,
  // endDateString: number,
  // hasTimeLimit: boolean,
  // ID: 3,
  // isAvailableToAllAcademics: boolean,
  // PhysicalObjects: string,
  // positionType: string,
  // prefecture: string,
  // prefectureID: number,
  // startDate: string,
  // startDateString: string,
  // supervisor: string,
  // supervisorEmail: string,
  // timeLimit: string,
  // title: string,
  // positionGroupLastUpdateString: string,
  // providerAFM: string,
  // providerContactEmail: string,
  // providerContactName: string,
  // providerContactPhone:string,
  // providerID: number,
  // providerName: string,
  // providerLastUpdateString: string;
}
