export interface Contract {
  contract_date: string;
  company_name: string;
  company_afm: string;
  company_address: string;
  company_liaison: string;
  company_liaison_position: string;
  displayname: string;
  father_name: string;
  dept_name: string;
  id_number: string;
  amika: string;
  amka: string;
  afm: string;
  doy_name: string;
  pa_subject: string;
  pa_subject_atlas: string;
  pa_start_date: string;
  pa_end_date: string;
  department_manager_name: string;
  ada_number?: string;
  student_wages?: string;
  apofasi?: string;
  arithmos_sunedriashs?: string;
  student_id?: string;
  assignment_ada_number?: string;
  assignment_apofasi?: string;
  assignment_arithmos_sunedriashs?: string;
  assigned_position_id?: number
}
